project_name: xxx项目名称
env: 测试环境
tester_name: abc

host:
  gateway_host: https://xx1.com
  lawyer_host: https://xx2.com
  callback_host: https://xx3.com
# 数据库相关配置
mysql:
  switch: true
  db: db
  host: host
  port: 30001
  user: root
  pwd: 1234
# redis相关配置
redis:
  host: host
  port: 30020
  pwd: 1234
  db: 0
# 邮箱相关配置
email:
  host: 192.168.188.53
  port: 465
  user: user01@james.com
  password: user01
  sender: 测试<x@qq.com>
  receivers: [ 'user02@james.com' ]
  receivers_list: [ 'user02@james.com','user03@james.com' ]
  to: 自动化测试

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
# 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
notification_type: 2
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False


# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token:a59902a7e811f93ffe301d8326b07a2acc8aa2a864e7d61ee9fc076481ced2a6
  secret: SECdea6489dfcc3b9259da943c5ae38d3530696f2fa83ac72a9ee716e9511675b9b
#  webhook:
#  secret:


# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=413f6e2d-4a16-4598-b11c-40c1f54aa111


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍

# 飞书通知
lark:
  webhook:



